version: '3.8'

services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    image: rinha-backend:latest
    command: echo "Image built successfully"

  rinha-backend:
    image: rinha-backend:latest
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
